version: 1
labels:
- label: "type/feature"
  title: "^feat.*"
- label: "type/fix"
  title: "^fix.*"
- label: "type/refactor"
  title: "^refactor.*"
- label: "type/style"
  title: "^style.*"
- label: "type/chore"
  title: "^chore.*"
- label: "type/perf"
  title: "^perf.*"
- label: "type/build"
  title: "^build.*"
- label: "type/revert"
  title: "^revert.*"
- label: "component/ci"
  title: "^ci.*"
- label: "component/test"
  title: "^test.*"
- label: "component/doc"
  title: "^doc.*"
- label: "type/deprecate"
  title: "^deprecate.*"

# If it's removed, or ticked.
- label: "user-facing-changes"
  negate: true
  body: 'My PR contains user-facing changes'
- label: "user-facing-changes"
  body: '- \[x\] My PR contains user-facing changes'

- label: "breaking-change"
  body: '- \[x\] My PR contains breaking changes'
