[package]
name = "risingwave_bench"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
async-trait = "0.1"
aws-config = { workspace = true }
aws-credential-types = { workspace = true }
aws-sdk-s3 = { workspace = true }
aws-smithy-http = { workspace = true }
bcc = { version = "0.0.33", optional = true }
bytes = "1"
bytesize = { version = "1", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
futures = { version = "0.3", default-features = false, features = ["alloc"] }
hdrhistogram = "7"
isahc = { version = "1", default-features = false }
itertools = "0.10"
libc = "0.2"
opentelemetry = { version = "0.17", optional = true, features = ["rt-tokio"] }
opentelemetry-jaeger = { version = "0.16", optional = true, features = [
    "rt-tokio",
    "collector_client",
    "isahc",
    "isahc_collector_client",
] }
parking_lot = "0.12"
prometheus = { version = "0.13", features = ["process"] }
rand = "0.8"
risingwave_common = { path = "../common" }
risingwave_storage = { path = "../storage" }
serde = { version = "1", features = ["derive"] }
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "fs",
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
] }
tokio-stream = "0.1"
toml = "0.7"
tracing = "0.1"
tracing-opentelemetry = { version = "0.17", optional = true }
tracing-subscriber = "0.3.16"

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../workspace-hack" }

[target.'cfg(target_os = "linux")'.dependencies]
nix = { version = "0.25", features = ["fs", "mman"] }

[[bin]]
name = "file-cache-bench"
path = "file_cache_bench/main.rs"

[[bin]]
name = "s3-bench"
path = "s3_bench/main.rs"

[features]
bpf = ["bcc", "risingwave_storage/bpf"]
trace = ["opentelemetry", "opentelemetry-jaeger", "tracing-opentelemetry", "tracing/release_max_level_trace"]
