[package]
name = "risingwave_tracing"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.cargo-machete]
ignored = ["workspace-hack"]

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-hack"]

[dependencies]
anyhow = "1"
futures = { version = "0.3", default-features = false, features = ["alloc", "executor"] }
rand = "0.8"
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "sync",
    "macros",
    "time",
    "signal"
] }
tracing = "0.1"

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../workspace-hack" }
