[package]
name = "risingwave_compute"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["workspace-hack"]

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-hack"]

[dependencies]
anyhow = "1"
async-trait = "0.1"
await-tree = { workspace = true }
clap = { version = "4", features = ["derive"] }
either = "1"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
futures-async-stream = { workspace = true }
hyper = "0.14"
itertools = "0.10"
maplit = "1.0.2"
pprof = { version = "0.11", features = ["flamegraph"] }
prometheus = { version = "0.13" }
risingwave_batch = { path = "../batch" }
risingwave_common = { path = "../common" }
risingwave_common_service = { path = "../common/common_service" }
risingwave_connector = { path = "../connector" }
risingwave_hummock_sdk = { path = "../storage/hummock_sdk" }
risingwave_pb = { path = "../prost" }
risingwave_rpc_client = { path = "../rpc_client" }
risingwave_source = { path = "../source" }
risingwave_storage = { path = "../storage" }
risingwave_stream = { path = "../stream" }
risingwave_tracing = { path = "../tracing" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
    "fs",
] }
tokio-stream = "0.1"
tonic = { version = "0.2", package = "madsim-tonic" }
tower = { version = "0.4", features = ["util", "load-shed"] }
tracing = "0.1"
uuid = "1.2.2"

[target.'cfg(target_os = "linux")'.dependencies]
tikv-jemalloc-ctl = "0.5"

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../workspace-hack" }

[dev-dependencies]
futures-async-stream = { workspace = true }
rand = "0.8"
tempfile = "3"
