version: "3.9"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    ports:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    command: [ "postgres", "-c", "wal_level=logical" ]

  mysql:
    image: mysql:8.0
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -u root -p123456"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
  
  message_queue:
    image: "docker.vectorized.io/vectorized/redpanda:latest"
    command:
      - redpanda
      - start
      - "--smp"
      - "1"
      - "--reserve-memory"
      - 0M
      - "--memory"
      - 4G
      - "--overprovisioned"
      - "--node-id"
      - "0"
      - "--check=false"
      - "--kafka-addr"
      - "PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092"
      - "--advertise-kafka-addr"
      - "PLAINTEXT://message_queue:29092,OUTSIDE://localhost:9092"
    expose:
      - "29092"
      - "9092"
      - "9644"
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9644:9644"
      - "8081:8081"
    environment: {}
    container_name: message_queue
    healthcheck:
      test: curl -f localhost:9644/v1/status/ready
      interval: 1s
      timeout: 5s
      retries: 5

  source-test-env:
    image: public.ecr.aws/x5u3w5h6/rw-build-env:v20230531
    depends_on:
      - mysql
      - db
      - message_queue
    volumes:
      - ..:/risingwave

  sink-test-env:
    image: public.ecr.aws/x5u3w5h6/rw-build-env:v20230531
    depends_on:
      - mysql
      - db
    volumes:
      - ..:/risingwave

  rw-build-env:
    image: public.ecr.aws/x5u3w5h6/rw-build-env:v20230531
    volumes:
      - ..:/risingwave

  ci-flamegraph-env:
    image: public.ecr.aws/x5u3w5h6/rw-build-env:v20230531
    # NOTE(kwannoel): This is used in order to permit
    # syscalls for `nperf` (perf_event_open),
    # so it can do CPU profiling.
    # These options should NOT be used for other services.
    privileged: true
    userns_mode: host
    volumes:
      - ..:/risingwave

  regress-test-env:
    image: public.ecr.aws/x5u3w5h6/rw-build-env:v20230531
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ..:/risingwave

  release-env:
    image: quay.io/pypa/manylinux2014_x86_64
    working_dir: /mnt
    volumes:
      - ..:/mnt
