[package]
name = "risingwave_storage"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["workspace-hack"]

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-hack"]

[dependencies]
arc-swap = "1"
async-trait = "0.1"
auto_enums = { version = "0.8", features = ["futures03"] }
await-tree = { workspace = true }
bytes = { version = "1", features = ["serde"] }
crossbeam = "0.8.1"
dashmap = { version = "5", default-features = false }
dyn-clone = "1.0.4"
enum-as-inner = "0.5"
fail = "0.5"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
futures-async-stream = { workspace = true }
hex = "0.4"
itertools = "0.10"
libc = "0.2"
lz4 = "1.23.1"
memcomparable = "0.2"
num-integer = "0.1"
parking_lot = "0.12"
prometheus = { version = "0.13", features = ["process"] }
prost = "0.11"
rand = "0.8"
risingwave_backup = { path = "../storage/backup" }
risingwave_common = { path = "../common" }
risingwave_common_service = { path = "../common/common_service" }
risingwave_hummock_sdk = { path = "../storage/hummock_sdk" }
risingwave_hummock_trace = { path = "../storage/hummock_trace" }
risingwave_object_store = { path = "../object_store" }
risingwave_pb = { path = "../prost" }
risingwave_rpc_client = { path = "../rpc_client" }
risingwave_tracing = { path = "../tracing" }
scopeguard = "1"
sled = "0.34.7"
spin = "0.9"
sync-point = { path = "../utils/sync-point" }
sysinfo = { version = "0.26", default-features = false }
tempfile = "3"
thiserror = "1"
# tikv-client = { git = "https://github.com/tikv/client-rust", rev = "5714b2", optional = true }
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "fs",
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
] }
tokio-retry = "0.3"
tracing = "0.1"
xorf = "0.8.1"
xxhash-rust = { version = "0.8.5", features = ["xxh32", "xxh64"] }
zstd = { version = "0.12", default-features = false }

[target.'cfg(target_os = "linux")'.dependencies]
procfs = { version = "0.14", default-features = false }
libc = "0.2"
nix = { version = "0.25", features = ["fs", "mman"] }

[target.'cfg(target_os = "macos")'.dependencies]
darwin-libproc = { git = "https://github.com/risingwavelabs/darwin-libproc.git", rev = "a502be24bd0971463f5bcbfe035a248d8ba503b7" }
libc = "0.2.72"
mach2 = "0.4"

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../workspace-hack" }

[dev-dependencies]
criterion = { version = "0.4", features = ["async_futures"] }
moka = { version = "0.10", features = ["future"] }
risingwave_test_runner = { path = "../test_runner" }
uuid = { version = "1", features = ["v4"] }

[target.'cfg(target_os = "linux")'.dev-dependencies]
fiemap = "0.1.1"

[features]
# rocksdb-local = ["rocksdb"]
# tikv = ["tikv-client"]
test = []
failpoints = ["fail/failpoints"]
bpf = []

[[bench]]
name = "bench_block_iter"
harness = false
# Enable debug if you want to generate flamegraph.
# debug = true

[[bench]]
name = "bench_lru_cache"
harness = false

[[bench]]
name = "bench_merge_iter"
harness = false

[[bench]]
name = "bench_fs_operation"
harness = false

[[bench]]
name = "bench_compression"
harness = false

[[bench]]
name = "bench_compactor"
harness = false

[[bench]]
name = "bench_multi_builder"
harness = false
